version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bookrex-db
    restart: always
    environment:
      POSTGRES_USER: bookrex
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: books
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
